spring.application.name=gestrec
spring.profiles.active=${APP_PROFILE:dev}

jwt.secret=MinhaChaveSecretaParaJWTQueDeveSerMuitoSeguraEComplexa123!
jwt.expiration-ms=3600000

# Springdoc / Swagger UI configs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Ordenacao: usar ordenacao alfanumerica
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha